name: Run tests

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Dockerfile'
      - 'entrypoint.sh'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'Dockerfile'
      - 'entrypoint.sh'
  workflow_dispatch:

env:
  PACKAGE_VERSION: "1.0.${{ github.run_number }}"
  IMAGE_RELEASE: "v1.0.0-test"
  USER: ${{ github.actor }}
  NAMESPACE: 'cpintado-org'

jobs:
  test-publish-dotcom:
    runs-on: ubuntu-latest
    name: Publish a package to github.com
    env:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/${{ github.repository }}:$IMAGE_RELEASE
    - name: Publish a package
      run: |
        docker run -e USER -e TOKEN -e NAMESPACE \
        -e PACKAGE_VERSION \
        ghcr.io/${{ github.repository }}:$IMAGE_RELEASE
  test-publish-ghes-subdomain:
    runs-on: ubuntu-latest
    name: Publish a package to a GHES instance with subdomain isolation enabled
    env:
      TOKEN: ${{ secrets.GHES_PAT }}
      GHES_HOSTNAME: ${{ vars.GHES_INSTANCE }}
      REPOSITORY_URL: "https://${{ vars.GHES_INSTANCE }}/${{ env.NAMESPACE }}/test-packages"
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/${{ github.repository }}:$IMAGE_RELEASE
    - name: Publish a package
      run: |
        docker run -e USER -e TOKEN -e NAMESPACE -e GHES_HOSTNAME \
        -e PACKAGE_VERSION \
        -e REPOSITORY_URL \
        ghcr.io/${{ github.repository }}:$IMAGE_RELEASE
  test-publish-ghes-subdomain-disabled:
    runs-on: ubuntu-latest
    name: Publish a package to a GHES instance with subdomain isolation disabled
    env:
      TOKEN: ${{ secrets.GHES_PAT_NO_SUBDOMAIN }}
      GHES_HOSTNAME: ${{ vars.GHES_INSTANCE__NO_SUBDOMAIN }}
      REPOSITORY_URL: "https://${{ vars.GHES_INSTANCE_NO_SUBDOMAIN }}/${{ env.NAMESPACE }}/test-packages"
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/${{ github.repository }}:$IMAGE_RELEASE
    - name: Publish a package
      run: |
        docker run -e USER -e TOKEN -e NAMESPACE -e GHES_HOSTNAME \
        -e SUBDOMAIN_ISOLATION -e PACKAGE_VERSION \
        -e REPOSITORY_URL \
        ghcr.io/${{ github.repository }}:$IMAGE_RELEASE
